window.skillsData = [
  { name: "HTML5", icon: "image/HTML.webp", category: "Markup", stagger: 1, tier: "core" },
  { name: "CSS3", icon: "image/CSS.webp", category: "Styling", stagger: 2, tier: "core" },
  { name: "JavaScript", icon: "image/javascript-logo.webp", category: "Logic", stagger: 3, tier: "core" },
  { name: "TypeScript", icon: "https://skillicons.dev/icons?i=ts", category: "Typing", stagger: 4, tier: "core" },
  { name: "React.js", icon: "image/react-logo.webp", category: "Library", stagger: 1, tier: "core" },
  { name: "Next.js", icon: "https://skillicons.dev/icons?i=nextjs", category: "Framework", stagger: 2, tier: "core" },
  { name: "Tailwind", icon: "image/Tailwind_CSS_Logo.webp", category: "Utility CSS", stagger: 3, tier: "core" },
  { name: "Bootstrap", icon: "https://skillicons.dev/icons?i=bootstrap", category: "CSS Toolkit", stagger: 4, tier: "familiar" },
  { name: "MUI", icon: "https://skillicons.dev/icons?i=materialui", category: "Component UI", stagger: 1, tier: "familiar" },
  { name: "Shadcn/ui", icon: "https://cdn.simpleicons.org/shadcnui", category: "Modern UI", stagger: 2, tier: "familiar" },
  { name: "PHP", icon: "image/php.webp", category: "Backend", stagger: 3, tier: "core" },
  { name: "Laravel", icon: "https://cdn.simpleicons.org/laravel", brand: "FF2D20", category: "Framework", stagger: 4, tier: "core" },
  { name: "MySQL", icon: "https://cdn.simpleicons.org/mysql", brand: "4479A1", category: "Database", stagger: 1, tier: "core" },
  { name: "SQLite", icon: "https://cdn.simpleicons.org/sqlite", brand: "003B57", category: "Embed DB", stagger: 2, tier: "familiar" },
  // { name: "FastAPI", icon: "https://skillicons.dev/icons?i=fastapi", category: "Python API", stagger: 3 },
  { name: "REST API", icon: "https://skillicons.dev/icons?i=postman", category: "Integration", stagger: 4, tier: "core" },
  // { name: "Webhooks", icon: "https://cdn.simpleicons.org/webhooks", category: "Syncing", stagger: 1 },
  { name: "Make.com", icon: "https://cdn.simpleicons.org/make", category: "Automation", stagger: 2, tier: "familiar" },
  { name: "Git", icon: "image/git.webp", category: "Versioning", stagger: 3, tier: "core" },
  { name: "GitHub", icon: "https://cdn.simpleicons.org/github", brand: "181717", category: "VCS Host", stagger: 4, tier: "core" },
  { name: "Vercel", icon: "https://skillicons.dev/icons?i=vercel", category: "Deployment", stagger: 1, tier: "core" },
  { name: "Nginx", icon: "https://skillicons.dev/icons?i=nginx", category: "Server", stagger: 2, tier: "familiar" },
  { name: "PM2", icon: "https://cdn.simpleicons.org/pm2", category: "Lifecycle", stagger: 3, tier: "familiar" },
  // { name: "MS Office", icon: "image/ms-office.webp", category: "Productivity", stagger: 4 },
  // { name: "Jira", icon: "https://skillicons.dev/icons?i=jira&theme=dark", category: "Agile Tool", stagger: 1 },
  // { name: "Zoho", icon: "https://cdn.simpleicons.org/zoho/white", category: "Management", stagger: 2 },
  { name: "Agile", icon: "groups", category: "Workflow", stagger: 3, isMaterialIcon: true, tier: "core" }
];
