window.skillsData = [
  { name: "HTML5", icon: "image/HTML.png", category: "Markup", stagger: 1 },
  { name: "CSS3", icon: "image/CSS.png", category: "Styling", stagger: 2 },
  { name: "JavaScript", icon: "image/javascript-logo.png", category: "Logic", stagger: 3 },
  { name: "TypeScript", icon: "https://skillicons.dev/icons?i=ts&theme=dark", category: "Typing", stagger: 4 },
  { name: "React.js", icon: "image/react-logo.png", category: "Library", stagger: 1 },
  { name: "Next.js", icon: "https://skillicons.dev/icons?i=nextjs&theme=dark", category: "Framework", stagger: 2 },
  { name: "Tailwind", icon: "image/Tailwind_CSS_Logo.png", category: "Utility CSS", stagger: 3 },
  { name: "Bootstrap", icon: "https://skillicons.dev/icons?i=bootstrap&theme=dark", category: "CSS Toolkit", stagger: 4 },
  { name: "MUI", icon: "https://skillicons.dev/icons?i=materialui&theme=dark", category: "Component UI", stagger: 1 },
  { name: "Shadcn/ui", icon: "https://cdn.simpleicons.org/shadcnui/white", category: "Modern UI", stagger: 2 },
  { name: "PHP", icon: "image/php.png", category: "Backend", stagger: 3 },
  { name: "Laravel", icon: "image/Laravel.png", category: "Framework", stagger: 4 },
  { name: "MySQL", icon: "image/mysql.png", category: "Database", stagger: 1 },
  { name: "SQLite", icon: "image/sqlite.png", category: "Embed DB", stagger: 2 },
  // { name: "FastAPI", icon: "https://skillicons.dev/icons?i=fastapi&theme=dark", category: "Python API", stagger: 3 },
  { name: "REST API", icon: "https://skillicons.dev/icons?i=postman&theme=dark", category: "Integration", stagger: 4 },
  // { name: "Webhooks", icon: "https://cdn.simpleicons.org/webhooks/white", category: "Syncing", stagger: 1 },
  { name: "Make.com", icon: "https://cdn.simpleicons.org/make/white", category: "Automation", stagger: 2 },
  { name: "Git", icon: "image/git.png", category: "Versioning", stagger: 3 },
  { name: "GitHub", icon: "image/github.png", category: "VCS Host", stagger: 4 },
  { name: "Vercel", icon: "https://skillicons.dev/icons?i=vercel&theme=dark", category: "Deployment", stagger: 1 },
  { name: "Nginx", icon: "https://skillicons.dev/icons?i=nginx&theme=dark", category: "Server", stagger: 2 },
  { name: "PM2", icon: "https://cdn.simpleicons.org/pm2/white", category: "Lifecycle", stagger: 3 },
  // { name: "MS Office", icon: "image/ms-office.png", category: "Productivity", stagger: 4 },
  // { name: "Jira", icon: "https://skillicons.dev/icons?i=jira&theme=dark", category: "Agile Tool", stagger: 1 },
  // { name: "Zoho", icon: "https://cdn.simpleicons.org/zoho/white", category: "Management", stagger: 2 },
  { name: "Agile", icon: "groups", category: "Workflow", stagger: 3, isMaterialIcon: true }
];
