/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./code.html", "./portfolio-data.js", "./skills-data.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--surface-variant)",
        "tertiary": "var(--tertiary)",
        "on-surface": "var(--on-surface)",
        "secondary-fixed": "var(--secondary-fixed)",
        "error": "var(--error)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-tint": "var(--surface-tint)",
        "tertiary-container": "var(--tertiary-container)",
        "primary-fixed": "var(--primary-fixed)",
        "on-background": "var(--on-background)",
        "surface-bright": "var(--surface-bright)",
        "on-secondary-container": "var(--on-secondary-container)",
        "primary-container": "var(--primary-container)",
        "surface-container": "var(--surface-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "secondary-container": "var(--secondary-container)",
        "background": "var(--background)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-error": "var(--on-error)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-primary": "var(--on-primary)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary": "var(--on-tertiary)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-dim": "var(--surface-dim)",
        "outline-variant": "var(--outline-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-secondary": "var(--on-secondary)",
        "surface": "var(--surface)",
        "surface-container-high": "var(--surface-container-high)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "inverse-primary": "var(--inverse-primary)",
        "primary": "var(--primary)",
        "outline": "var(--outline)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "error-container": "var(--error-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "secondary": "var(--secondary)"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"],
        "fancy": ["Syne"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
